### ISSUE TITLE
Unable to get Plugin working

### ISSUE THREAD

**Issue by demokedes** [davidegiacometti/PowerToys-Run-EdgeFavorite#1]
I am new to PowerToys Run. 
I like the description of plugin. I would really like to get Edge bookmarks showin PTRun. 
I am using v0.70.1.
I am following instruction. Extract the content of zip file into %LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins
Restart the PowerToys, but than nothing happens. 
I don't see it under plugins and also if start writing after @, no bookmark is showing up.
Am I missing something? I am new to PowerToys, therefore It is possible I am missing some prerequisite. Please give me some guidance. 
Thank you in advance,
Rok

**Comment by davidegiacometti** [comment]
Hi @demokedes 
If you don't see the plugin in PowerToys settings probably isn't installed in the correct folder.

![image](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/assets/25966642/711bf5c4-eff5-4bc6-9a8b-11c3f03b6a1c)

The plugin is supposed to be copied in `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\EdgeFavorite` (note the `EdgeFavorite` folder).

If still don't work you can try to copy in the PowerToys install folder (default `C:\Program Files\PowerToys\modules\launcher\Plugins`).

**Comment by demokedes** [comment]
Dear Davide,
Thank you very much for your reply.
I renamed the folder as suggested, but still not success. I even tried with both paths.

  1.  Is it possible, I am not pasting the right content? Should I paste zip file in the folder, extract the whole content or just  “Community.PowerToys.Run.Plugin.EdgeFavorite” folder?
  2.  Is it possible, it is not working because I am using PowerToys (Preview) version?
  3.  Is there any log, I can check to see, what is the reason?
[A screenshot of a computer  Description automatically generated with medium confidence]
[A screenshot of a computer  Description automatically generated with medium confidence]

**Comment by davidegiacometti** [comment]
You don't have to paste the `Community.PowerToys.Run.Plugin.EdgeFavorite`. That folder is the source code.
Download the latest x64 or ARM64 release (based on your CPU):
- https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/download/0.0.1/EdgeFavorite-0.0.1-x64.zip 
- https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/download/0.0.1/EdgeFavorite-0.0.1-ARM64.zip

Just extract the zip in `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins`.
You should have the following folders/files:

![image](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/assets/25966642/c97ac3ce-d963-48bf-8f7a-0e5b926d48b1)

**Comment by demokedes** [comment]
Davide,
Thank you very much!
It is working like a charm! Verry happy! 😊
Regards

**Comment by davidegiacometti** [comment]
Happy to know that you have been able to make the plugin working and that you find it useful.
I will consider improving the installation instructions.
