### ISSUE TITLE
[Bug] Failed to load bookmark other than default

### ISSUE THREAD

**Issue by 8LWXpg** [davidegiacometti/PowerToys-Run-EdgeFavorite#10]
All my bookmarks are located under `Profile 1`. When I launch PowerToys, it displays an empty list, but it works as expected once I toggle the `Default profile only` setting on and then off again.

And for settings, I think it might be better to have the ability to set a list of profiles to load bookmarks.

**Comment by davidegiacometti** [comment]
I don't really use multiple profile and this feature broke during a refactoring.
I have just released the fix in [0.5.2](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/tag/0.5.2)

Not planning to implement an options to chose the profiles to avoid too much coupling of settings to profiles.
If you believe this is necessary, could you please create a separate issue to keep track of it?
I will then take some time to consider how best to implement it in the future.
Thank you!
