### ISSUE TITLE
[Feature] Setting for profile

### ISSUE THREAD

**Issue by 8LWXpg** [davidegiacometti/PowerToys-Run-EdgeFavorite#11]
As mentioned in #10

Add a setting to select one (or multiple) profile to load bookmarks from, replacing `Default profile only` option.

**Comment by davidegiacometti** [comment]
I have just released version [0.6.0](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/tag/0.6.0) with the suggested feature.
The new release requires PowerToys 0.81.0 or newer.
