### ISSUE TITLE
Documentation for developer loop

### ISSUE THREAD

**Issue by ghost** [davidegiacometti/PowerToys-Run-EdgeFavorite#14]
Would you consider adding some documentation to help developers get started on contributing to this (awesome) plugin?
Such documentation might point to the PowerToys repository itself, but I'd be curious to know what your inner-dev-loop is like from initial local machine setup to debugging.

**Comment by davidegiacometti** [comment]
Hi @0x34353534

There is nothing special about the dev loop: the plugin should be easy to build without any special requirements.
Once built, it can be deployed in the PowerToys Run folder: https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite?tab=readme-ov-file#installation
You can also attach to `PowerToys.PowerLauncher.exe` process to debug it. 😉 

PowerToys Run dev docs can be found in the official repository: https://github.com/microsoft/PowerToys/tree/main/doc/devdocs/modules/launcher

I Hope it helps.
