### ISSUE TITLE
Support for "synced" and "workspaces" bookmakrs

### ISSUE THREAD

**Issue by 8LWXpg** [davidegiacometti/PowerToys-Run-EdgeFavorite#15]
In my `Bookmarks`, the `synced` (bookmarks from mobile) and `workspaces` (bookmarks from workspaces) field under the `root` field are not detected by the plugin.

**Comment by davidegiacometti** [comment]
Released in [0.8.0](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/tag/0.8.0)
Thanks again for the contribution!
