### ISSUE TITLE
Support for other branches of Edge (Beta, Dev, Canary)

### ISSUE THREAD

**Issue by NaitorStudios** [davidegiacometti/PowerToys-Run-EdgeFavorite#17]
Could you please add this? Because I really don't use the Stable release...

**Comment by davidegiacometti** [comment]
Hi @NaitorStudios

Thanks for the suggestion!
I knew that at some point someone would ask for this feature 😄 

Do you think that an option to choose a single Edge channel to use between Stable, Beta, Dev, Canary would be enough to cover your use case?

**Comment by NaitorStudios** [comment]
Yeah, I think it would become a bit messy if there was multiple channels, idk, so picking one should be enough. Thank you!

**Comment by davidegiacometti** [comment]
> Yeah, I think it would become a bit messy if there was multiple channels

I was thinking the same: let's keep it simple and implement a single channel.

I'll try to look into that and release a preview version of the plugin with the new feature.

**Comment by davidegiacometti** [comment]
Hey @NaitorStudios 
I have just released [0.8.0](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/tag/0.8.0) 🚀 
Any feedback is appreciated! 😃

**Comment by NaitorStudios** [comment]
Thank you so much for the quick support. I've just switched from Wox/Flow to PowerToys Run because of the third-party plugin support, really nice to already see so many interesting plugins!

**Comment by davidegiacometti** [comment]
I have just released stable [0.9.0](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/tag/0.9.0) that includes this feature.
