### ISSUE TITLE
No results from within folders

### ISSUE THREAD

**Issue by jnoynaert** [davidegiacometti/PowerToys-Run-EdgeFavorite#2]
Nested results don't return as shown in the readme.

![image](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/assets/5920864/e754ee20-ebef-46cd-938c-3eb96b52d8d7)

PowerToys v0.71.0

**Comment by davidegiacometti** [comment]
Hi @jnoynaert 

Can you elaborate on the issue?
- What's the actual behavior? No results? Partial results?
- Are you able to see your favorites disabling "Search as tree"?

Sharing the latest log from `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Logs\0.71.0.0` may help.

**Comment by jnoynaert** [comment]
Turning off search as tree made it work as desired (all bookmarks are now searchable even if nested in folders). Previously it was showing the folder names but not any contents. Thanks!

**Comment by davidegiacometti** [comment]
With the "Search as tree" option enabled you are supposed to search the favorites like a file system:
- `@FOLDER-NAME/`
- `@FOLDER-NAME/FAVORITE-NAME`
