### ISSUE TITLE
The bug 'Fail to load plugin' still exists in PowerToys v0.75.1.

### ISSUE THREAD

**Issue by wuziqiu666** [davidegiacometti/PowerToys-Run-EdgeFavorite#4]
❤

**Comment by davidegiacometti** [comment]
Hi @wuziqiu666 
PowerToys 0.75.0 and newer require the latest release of the plugin.
Replace the installed version with [0.1.0](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/tag/0.1.0) release.
