### ISSUE TITLE
Support for multiple Edge profiles

### ISSUE THREAD

**Issue by philmargetts** [davidegiacometti/PowerToys-Run-EdgeFavorite#6]
Hi there, great plugin! Ever thought about supporting multiple profiles? eg work/admin/personal
If not, I might get around to having a look...
Cheers!

**Comment by davidegiacometti** [comment]
Hi @philmargetts 

First of all, I'm glad you like the plugin! 😃 
I never thought about supporting multiple profiles but I would be happy to see a PR if you or somebody else would like to implement this feature.

**Comment by davidegiacometti** [comment]
Hi @philmargetts 

I have just released a pre-release of the plugin that introduce the support for multiple Edge profiles: https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/tag/0.3.0

Any feedback would be appreciated.

**Comment by nathanm412** [comment]
It works well for me. Thanks!

**Comment by philmargetts** [comment]
Works perfectly, opens in the correct profile and everything. Thank you!

**Comment by davidegiacometti** [comment]
I am glad that it's working! 🚀

I will keep the new feature in pre-release for a while and will leave this issue open for feedbacks.

**Comment by davidegiacometti** [comment]
I am going to close this issue since I have just released version [0.4.0](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/tag/0.4.0) with stable Edge profiles support.
