### ISSUE TITLE
[Feature] Enter to complete folder query when search as tree is on

### ISSUE THREAD

**Issue by 8LWXpg** [davidegiacometti/PowerToys-Run-EdgeFavorite#7]
I want the search query to be completed with a slash (/) when I press enter on a folder, so that it shows the folder content.

for example, if there's a folder `folder`, it should complete query with `@ folder/` and show the query of it.

**Comment by davidegiacometti** [comment]
Hi @8LWXpg

Thanks for the suggestion, it sounds interesting and feasible.
For technical reasons this feature will require the next release of PowerToys (0.79.0) that should be released early march.

Stay tuned! 🚀

**Comment by davidegiacometti** [comment]
I have just released version [0.4.0](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite/releases/tag/0.4.0) that includes this suggestion.
